config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :check_ups
  get '/', to: 'home#index', as: 'home'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_up.rb
class CheckUp < ApplicationRecord
  validates :security_engineer_name, presence: true
  validates :account_manager_name, presence: true
  validates :partner_name, presence: true
  validates :original_file_name, presence: true
  validates :file_uuid, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end
  

app/controllers/check_ups_controller.rb
class CheckUpsController < ApplicationController
  
  def new
    @checkup = CheckUp.new()
  end
  
  
  def create
	
    @checkup = CheckUp.new(
    security_engineer_name: params[:check_up][:security_engineer_name],
    account_manager_name: params[:check_up][:account_manager_name],
    partner_name: params[:check_up][:partner_name],
    original_file_name: params[:check_up][:filename].original_filename,
    file_uuid: SecureRandom.uuid)
    
    @checkup.save
    if @checkup.errors.any?
      flash[:error] = @checkup.errors
      render 'new'
    else
	  uploaded_file = params[:check_up][:filename]
	  File.open(Rails.root.join('public', 'uploads', @checkup.file_uuid + File.extname(uploaded_file.original_filename)), 'wb') do |file|
	    file.write(uploaded_file.read)
	  end
      redirect_to home_path
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @scus = CheckUp.where("created_at > ?", Time.now.at_beginning_of_quarter )
    #retrieve all checkups for current quarter
    
  end
  
  
  


end

app/helpers/application_helper.rb
module ApplicationHelper

  def q_number(date)
    q = (date.month / 3.0).ceil
	return q
  end
	
end

app/helpers/check_ups_helper.rb
module CheckUpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/check_ups/_check_up.html.erb
<tr>
  <td><%= check_up.created_at %></td>
  <td><%= check_up.security_engineer_name %></td>
  <td><%= check_up.account_manager_name %></td>
  <td><%= check_up.partner_name %></td>
  <td><%= link_to "Download", '/uploads/' + check_up.file_uuid + File.extname(check_up.original_file_name), class: 'btn btn-success' %></td>
</tr>

app/views/check_ups/new.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <h2>New Security CheckUp</h2>
  </div>
</div>
<% if flash[:error] %>
 
<% end %>
<div class='row'>
  <div class='col-xs-4'>
    <%= form_for @checkup do |f| %>
      <div class='form-group'>
        <%= f.label :security_engineer_name, "SE Name" %>
        <%= f.text_field :security_engineer_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
      <%= f.label "Account Manager Name"%>
      <%= f.text_field :account_manager_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
      <%= f.label "Partner Name"%>
      <%= f.text_field :partner_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
      <%= f.label "Upload file"%>
      <%= f.file_field :filename, class: 'form-control' %>
      </div>
      <%= f.submit "Upload", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class='row'>
	<div class='col-xs-3'>
		<h2>Security CheckUps</h2>
	</div>
</div>
<div class='row'>

	<div class='col-xs-3'>
	<h3>Current Quarter:<b> Q<%= q_number(Date.today) %></b></h3>
	</div>
	</div>
<br>
<br>
<div class='row'>
<div class='col-xs-12'>
<table class='table table-bordered table-striped'>
  <tr>
  <th>Date added</th><th>Security Engineer</th><th>Account Manager</th><th>Partner</th><th>Link to CheckUp</th>
</tr>
<%= render @scus %>
</table>
</div>
</div>
<hr>
<div class='row'>
<div class='col-xs-3'>
<%= link_to("Upload new SCU", new_check_ups_path, class: 'btn btn-success') %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Security CheckUp Portal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class='container-fluid'>
	<%= yield %>
	</div>
    
  </body>
</html>